/********************************************************************************************************************
 * Create By  : Pooja P Bhat
 * Description: Utility class to define all the Constants
 * CHANGE LOG
 * Date         Story#      ModifiedBy      Reason
 * 15-5-2023                Pooja P Bhat    Created.
 *******************************************************************************************************************/
public class SQX_ConstantsUtility {
	
    public static final String HIGH_VOLUME          =	'High Volume';
    public static final String LOW_VOLUME           =	'Low Volume';
    public static final Integer PARTS_UPPERBOUND    = 	99;

    public static final String INTEGRATION_ADMIN    =   'Integration_Admin';
}